### ISSUE TITLE
Conflicting dependencies when installing

### ISSUE THREAD

**Issue by AtomicNess123** [debanjum/khoj#97]
How to fix this problem?
```
ERROR: Cannot install khoj-assistant==0.1.0, khoj-assistant==0.1.2, khoj-assistant==0.1.3 and khoj-assistant==0.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    khoj-assistant 0.1.4 depends on numpy==1.22.4
    khoj-assistant 0.1.3 depends on numpy==1.22.4
    khoj-assistant 0.1.2 depends on numpy==1.22.4
    khoj-assistant 0.1.0 depends on numpy==1.22.4

```

**Comment by debanjum** [comment]
What command are you running to install khoj? A bit strange that there are multiple, older versions of `khoj` that it's attempting to install. The recommended way to install khoj is by running `pip install --upgrade khoj-assistant`

**Comment by AtomicNess123** [comment]
Thanks for the fast response. I am using the following:

`pip install khoj-assistant`

**Comment by debanjum** [comment]
Could you run `pip uninstall khoj-assistant && pip install --no-cache-dir
--upgrade khoj-assistant`?
Just to ensure there's no pip related caching issues we're seeing on your
side

**Comment by AtomicNess123** [comment]
Thanks.

I get this:

§ pip uninstall khoj-assistant && pip install --no-cache-dir --upgrade khoj-assistant                                           127 ✘  

```shell
WARNING: Skipping khoj-assistant as it is not installed.
Collecting khoj-assistant
  Downloading khoj_assistant-0.1.4-py3-none-any.whl (142 kB)
     |████████████████████████████████| 142 kB 216 kB/s 
Requirement already satisfied: pillow>=9.0.1 in ./opt/anaconda3/lib/python3.7/site-packages (from khoj-assistant) (9.0.1)
  Downloading khoj_assistant-0.1.3-py3-none-any.whl (142 kB)
     |████████████████████████████████| 142 kB 393 kB/s 
  Downloading khoj_assistant-0.1.2-py3-none-any.whl (142 kB)
     |████████████████████████████████| 142 kB 594 kB/s 
  Downloading khoj_assistant-0.1.0-py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 307 kB/s 
ERROR: Cannot install khoj-assistant==0.1.0, khoj-assistant==0.1.2, khoj-assistant==0.1.3 and khoj-assistant==0.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    khoj-assistant 0.1.4 depends on numpy==1.22.4
    khoj-assistant 0.1.3 depends on numpy==1.22.4
    khoj-assistant 0.1.2 depends on numpy==1.22.4
    khoj-assistant 0.1.0 depends on numpy==1.22.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by debanjum** [comment]
Ah, based on those logs
1. You're on an older python version (3.7). The newer versions of Khoj need python >= 3.8
2. You're running an anaconda python. Are you running the pip install command from within a conda environment?

Suggested fixes:
- You can fix `1.` by upgrading the installed version of python on your system/anaconda environment
- A different version of numpy is already installed that the one required by Khoj. Some ways to solve this are: 
   1. Installing Khoj in a separate virtualenv or conda environment. 
   2. Checking if it's safe to upgrade/downgrade numpy to `1.22.4` and manually doing that before trying to reinstall Khoj

**Comment by AtomicNess123** [comment]
Thanks! I did:

```
git clone https://github.com/debanjum/khoj && cd khoj
conda env create -f config/environment.yml
conda activate khoj
```

Then I tried to run khoj by typing its name... but nothing happened.

**Comment by AtomicNess123** [comment]
I tried to install khoj like this with khoj env active, and got this error:

```
§ pip install khoj-assistant
Traceback (most recent call last):
  File "/Users/User/opt/anaconda3/envs/khoj/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
  File "/Users/User/opt/anaconda3/envs/khoj/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/User/opt/anaconda3/envs/khoj/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Users/User/opt/anaconda3/envs/khoj/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/Users/User/opt/anaconda3/envs/khoj/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 13, in <module>
    import importlib.util
  File "/Users/User/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 51, in <module>
    _w_long = _bootstrap_external._w_long
AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'
```

**Comment by debanjum** [comment]
1. 
```
   File "/Users/User/opt/anaconda3/envs/khoj/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 13, in <module>
    import importlib.util
  File "/Users/User/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 51, in <module>
```
From the above error logs there seems to be an issue with your anaconda environment as both python3.7 and python3.8 libraries are being used in it.

2. 
> Then I tried to run khoj by typing its name... but nothing happened.

The instructions to setup Khoj using (ana-)conda are [here](https://github.com/debanjum/khoj#using-conda). According to that if you can start `khoj` by running `python3 -m src.main -vv` after you've setup the khoj conda environment. You shouldn't need to `pip install khoj-assistant` in the khoj conda environment.

3. The khoj setup with conda instructions maybe stale as I haven't tested this flow for a while. So let me try the conda environment setup flow on my end to see if I can reproduce your issue. I'll get back about this by the end of this week

**Comment by debanjum** [comment]
Updated [instructions to setup Khoj with Conda](https://github.com/debanjum/khoj#using-conda) in 676de2372eb9962437374b2750f5cc63076af5be. Verified setup with Conda works on an Ubuntu 22.04 machine.
Closing issue as no updates provided in a while
