### ISSUE TITLE
Error when installing khoj

### ISSUE THREAD

**Issue by smirnovmaksim91** [debanjum/khoj#140]
I have macOS Venture 13.1
When I run the command "pip install khoj-assistant && khoj --no-gui" in the terminal
I get the following error:
![Screenshot 2023-02-06 at 13 00 40](https://user-images.githubusercontent.com/70570280/216942307-7d23e290-9cde-4543-937c-526b3b8f954b.png)

`(.khoj_venv) (base) MacBook-Pro-Maksim:~ maksimsmirnov$ pip install khoj-assistant && khoj --no-gui
Requirement already satisfied: khoj-assistant in ./.khoj_venv/lib/python3.8/site-packages (0.2.5)
Requirement already satisfied: fastapi==0.77.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.77.1)
Requirement already satisfied: openai==0.20.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.20.0)
Requirement already satisfied: huggingface-hub==0.8.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.8.1)
Requirement already satisfied: uvicorn==0.17.6 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.17.6)
Requirement already satisfied: pyqt6==6.3.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (6.3.1)
Requirement already satisfied: torch==1.13.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (1.13.1)
Requirement already satisfied: aiofiles==0.8.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.8.0)
Requirement already satisfied: pillow==9.3.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (9.3.0)
Requirement already satisfied: numpy==1.22.4 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (1.22.4)
Requirement already satisfied: pydantic==1.9.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (1.9.1)
Requirement already satisfied: transformers==4.21.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (4.21.0)
Requirement already satisfied: schedule==1.1.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (1.1.0)
Requirement already satisfied: dateparser==1.1.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (1.1.1)
Requirement already satisfied: torchvision==0.14.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.14.1)
Requirement already satisfied: defusedxml==0.7.1 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (0.7.1)
Requirement already satisfied: sentence-transformers==2.1.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (2.1.0)
Requirement already satisfied: jinja2==3.1.2 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (3.1.2)
Requirement already satisfied: pyyaml==6.0 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (6.0)
Requirement already satisfied: pytest==7.1.2 in ./.khoj_venv/lib/python3.8/site-packages (from khoj-assistant) (7.1.2)
Requirement already satisfied: python-dateutil in ./.khoj_venv/lib/python3.8/site-packages (from dateparser==1.1.1->khoj-assistant) (2.8.2)
Requirement already satisfied: tzlocal in ./.khoj_venv/lib/python3.8/site-packages (from dateparser==1.1.1->khoj-assistant) (4.2)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,<2022.3.15 in ./.khoj_venv/lib/python3.8/site-packages (from dateparser==1.1.1->khoj-assistant) (2022.3.2)
Requirement already satisfied: pytz in ./.khoj_venv/lib/python3.8/site-packages (from dateparser==1.1.1->khoj-assistant) (2022.7.1)
Requirement already satisfied: starlette==0.19.1 in ./.khoj_venv/lib/python3.8/site-packages (from fastapi==0.77.1->khoj-assistant) (0.19.1)
Requirement already satisfied: tqdm in ./.khoj_venv/lib/python3.8/site-packages (from huggingface-hub==0.8.1->khoj-assistant) (4.64.1)
Requirement already satisfied: packaging>=20.9 in ./.khoj_venv/lib/python3.8/site-packages (from huggingface-hub==0.8.1->khoj-assistant) (23.0)
Requirement already satisfied: filelock in ./.khoj_venv/lib/python3.8/site-packages (from huggingface-hub==0.8.1->khoj-assistant) (3.9.0)
Requirement already satisfied: requests in ./.khoj_venv/lib/python3.8/site-packages (from huggingface-hub==0.8.1->khoj-assistant) (2.28.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.khoj_venv/lib/python3.8/site-packages (from huggingface-hub==0.8.1->khoj-assistant) (4.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.khoj_venv/lib/python3.8/site-packages (from jinja2==3.1.2->khoj-assistant) (2.1.2)
Requirement already satisfied: pandas>=1.2.3 in ./.khoj_venv/lib/python3.8/site-packages (from openai==0.20.0->khoj-assistant) (1.5.3)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in ./.khoj_venv/lib/python3.8/site-packages (from openai==0.20.0->khoj-assistant) (1.5.3.230203)
Requirement already satisfied: openpyxl>=3.0.7 in ./.khoj_venv/lib/python3.8/site-packages (from openai==0.20.0->khoj-assistant) (3.1.0)
Requirement already satisfied: PyQt6-sip<14,>=13.4 in ./.khoj_venv/lib/python3.8/site-packages (from pyqt6==6.3.1->khoj-assistant) (13.4.1)
Requirement already satisfied: PyQt6-Qt6>=6.3.0 in ./.khoj_venv/lib/python3.8/site-packages (from pyqt6==6.3.1->khoj-assistant) (6.4.2)
Requirement already satisfied: tomli>=1.0.0 in ./.khoj_venv/lib/python3.8/site-packages (from pytest==7.1.2->khoj-assistant) (2.0.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./.khoj_venv/lib/python3.8/site-packages (from pytest==7.1.2->khoj-assistant) (1.0.0)
Requirement already satisfied: iniconfig in ./.khoj_venv/lib/python3.8/site-packages (from pytest==7.1.2->khoj-assistant) (2.0.0)
Requirement already satisfied: py>=1.8.2 in ./.khoj_venv/lib/python3.8/site-packages (from pytest==7.1.2->khoj-assistant) (1.11.0)
Requirement already satisfied: attrs>=19.2.0 in ./.khoj_venv/lib/python3.8/site-packages (from pytest==7.1.2->khoj-assistant) (22.2.0)
Requirement already satisfied: tokenizers>=0.10.3 in ./.khoj_venv/lib/python3.8/site-packages (from sentence-transformers==2.1.0->khoj-assistant) (0.12.1)
Requirement already satisfied: scikit-learn in ./.khoj_venv/lib/python3.8/site-packages (from sentence-transformers==2.1.0->khoj-assistant) (1.2.1)
Requirement already satisfied: scipy in ./.khoj_venv/lib/python3.8/site-packages (from sentence-transformers==2.1.0->khoj-assistant) (1.10.0)
Requirement already satisfied: nltk in ./.khoj_venv/lib/python3.8/site-packages (from sentence-transformers==2.1.0->khoj-assistant) (3.8.1)
Requirement already satisfied: sentencepiece in ./.khoj_venv/lib/python3.8/site-packages (from sentence-transformers==2.1.0->khoj-assistant) (0.1.97)
Requirement already satisfied: click>=7.0 in ./.khoj_venv/lib/python3.8/site-packages (from uvicorn==0.17.6->khoj-assistant) (8.1.3)
Requirement already satisfied: asgiref>=3.4.0 in ./.khoj_venv/lib/python3.8/site-packages (from uvicorn==0.17.6->khoj-assistant) (3.6.0)
Requirement already satisfied: h11>=0.8 in ./.khoj_venv/lib/python3.8/site-packages (from uvicorn==0.17.6->khoj-assistant) (0.14.0)
Requirement already satisfied: anyio<5,>=3.4.0 in ./.khoj_venv/lib/python3.8/site-packages (from starlette==0.19.1->fastapi==0.77.1->khoj-assistant) (3.6.2)
Requirement already satisfied: et-xmlfile in ./.khoj_venv/lib/python3.8/site-packages (from openpyxl>=3.0.7->openai==0.20.0->khoj-assistant) (1.1.0)
Requirement already satisfied: types-pytz>=2022.1.1 in ./.khoj_venv/lib/python3.8/site-packages (from pandas-stubs>=1.1.0.11->openai==0.20.0->khoj-assistant) (2022.7.1.0)
Requirement already satisfied: six>=1.5 in ./.khoj_venv/lib/python3.8/site-packages (from python-dateutil->dateparser==1.1.1->khoj-assistant) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.khoj_venv/lib/python3.8/site-packages (from requests->huggingface-hub==0.8.1->khoj-assistant) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.khoj_venv/lib/python3.8/site-packages (from requests->huggingface-hub==0.8.1->khoj-assistant) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.khoj_venv/lib/python3.8/site-packages (from requests->huggingface-hub==0.8.1->khoj-assistant) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in ./.khoj_venv/lib/python3.8/site-packages (from requests->huggingface-hub==0.8.1->khoj-assistant) (3.4)
Requirement already satisfied: joblib in ./.khoj_venv/lib/python3.8/site-packages (from nltk->sentence-transformers==2.1.0->khoj-assistant) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.khoj_venv/lib/python3.8/site-packages (from scikit-learn->sentence-transformers==2.1.0->khoj-assistant) (3.1.0)
Requirement already satisfied: backports.zoneinfo in ./.khoj_venv/lib/python3.8/site-packages (from tzlocal->dateparser==1.1.1->khoj-assistant) (0.2.1)
Requirement already satisfied: pytz-deprecation-shim in ./.khoj_venv/lib/python3.8/site-packages (from tzlocal->dateparser==1.1.1->khoj-assistant) (0.1.0.post0)
Requirement already satisfied: sniffio>=1.1 in ./.khoj_venv/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette==0.19.1->fastapi==0.77.1->khoj-assistant) (1.3.0)
Requirement already satisfied: tzdata in ./.khoj_venv/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal->dateparser==1.1.1->khoj-assistant) (2022.7)
Traceback (most recent call last):
  File "/Users/maksimsmirnov/.khoj_venv/bin/khoj", line 5, in <module>
    from src.main import run
  File "/Users/maksimsmirnov/.khoj_venv/lib/python3.8/site-packages/src/main.py", line 23, in <module>
    from src.configure import configure_server
  File "/Users/maksimsmirnov/.khoj_venv/lib/python3.8/site-packages/src/configure.py", line 10, in <module>
    from src.processor.ledger.beancount_to_jsonl import BeancountToJsonl
  File "/Users/maksimsmirnov/.khoj_venv/lib/python3.8/site-packages/src/processor/ledger/beancount_to_jsonl.py", line 8, in <module>
    from src.processor.text_to_jsonl import TextToJsonl
  File "/Users/maksimsmirnov/.khoj_venv/lib/python3.8/site-packages/src/processor/text_to_jsonl.py", line 16, in <module>
    class TextToJsonl(ABC):
  File "/Users/maksimsmirnov/.khoj_venv/lib/python3.8/site-packages/src/processor/text_to_jsonl.py", line 21, in TextToJsonl
    def process(self, previous_entries: list[Entry]=None) -> list[tuple[int, Entry]]: ...
TypeError: 'type' object is not subscriptable
(.khoj_venv) (base) MacBook-Pro-Maksim:~ maksimsmirnov$ 
  [Restored Feb 6, 2023 at 12:55:03]
Last login: Mon Feb  6 12:40:52 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) MacBook-Pro-Maksim:~ maksimsmirnov$ pip install khoj-assistant && khoj --no-gui
Collecting khoj-assistant
  Using cached khoj_assistant-0.2.5-py3-none-any.whl (1.0 MB)
Collecting uvicorn==0.17.6
  Using cached uvicorn-0.17.6-py3-none-any.whl (53 kB)
Collecting pydantic==1.9.1
  Using cached pydantic-1.9.1-cp38-cp38-macosx_10_9_x86_64.whl (2.9 MB)
Collecting aiofiles==0.8.0
  Using cached aiofiles-0.8.0-py3-none-any.whl (13 kB)
Collecting schedule==1.1.0
  Using cached schedule-1.1.0-py2.py3-none-any.whl (10 kB)
Collecting pyqt6==6.3.1
  Using cached PyQt6-6.3.1.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/maksimsmirnov/opt/anaconda3/bin/python /Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/0b/x8_x9vqs1577tyyxjjw1dpg40000gn/T/tmpxagvmfau
         cwd: /private/var/folders/0b/x8_x9vqs1577tyyxjjw1dpg40000gn/T/pip-install-3j3cycbz/pyqt6
    Complete output (25 lines):
    Querying qmake about your Qt installation...
    Traceback (most recent call last):
      File "/Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/0b/x8_x9vqs1577tyyxjjw1dpg40000gn/T/pip-build-env-5m9c3u6g/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
        project = AbstractProject.bootstrap('wheel',
      File "/private/var/folders/0b/x8_x9vqs1577tyyxjjw1dpg40000gn/T/pip-build-env-5m9c3u6g/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/0b/x8_x9vqs1577tyyxjjw1dpg40000gn/T/pip-build-env-5m9c3u6g/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 601, in setup
        self.update(tool)
      File "project.py", line 164, in update
    sipbuild.exceptions.UserException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/maksimsmirnov/opt/anaconda3/bin/python /Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/0b/x8_x9vqs1577tyyxjjw1dpg40000gn/T/tmpxagvmfau Check the logs for full command output.`

**Comment by debanjum** [comment]
@smirnovmaksim91, there seem to be 2 different errors I see in the logs you shared

1. Running khoj failed with python 3.8 
    > File "/Users/maksimsmirnov/.khoj_venv/lib/python3.8/site-packages/src/processor/text_to_jsonl.py", line 21, in TextToJsonl
def process(self, previous_entries: list[Entry]=None) -> list[tuple[int, Entry]]: ...
TypeError: 'type' object is not subscriptable
 
   The [issue](https://github.com/debanjum/khoj/issues/130) with khoj not working with python3.8 was resolved [here](https://github.com/debanjum/khoj/commit/cba9a6a70348e07f016ab8665cbc3c2aed9f7462).
   You'll need to install the pre-release version of khoj (which tracks the master branch) to use that fix:
   ```shell
    # 1. Install the pre-release version of the Khoj backend with bug fix
    pip install --upgrade --pre khoj-assistant
    # 2. Start Khoj
    khoj --no-gui
   ```
3. Building the pyqt6 wheel failed while installing khoj.
    > Querying qmake about your Qt installation...
Traceback (most recent call last):
File "/Users/maksimsmirnov/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
hook = backend.prepare_metadata_for_build_wheel
AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    - It seems like you're trying to pip install khoj within an existing (ana-)conda environment? 
      In the first case, you seem to have successfully installed khoj from within a python virtual environment (`.khoj_venv`). But the run step failed because of the python 3.8 issue mentioned above. 
    - Try the suggested fix in 1. from within a python virtual environment instead of an anaconda environment. Hopefully that should get khoj installed and running for you with python 3.8

**Comment by smirnovmaksim91** [comment]
Thank you very much for your help. Everything is working!
