### ISSUE TITLE
Could not install khoj using python 3.11

### ISSUE THREAD

**Issue by usman-ghani-khan** [debanjum/khoj#128]
When  I try to add the `pip package` it shows the following error:

`ERROR: Cannot install khoj-assistant==0.1.0, khoj-assistant==0.1.10, khoj-assistant==0.1.2, khoj-assistant==0.1.3, khoj-assistant==0.1.4, khoj-assistant==0.1.5, khoj-assistant==0.1.6, khoj-assistant==0.1.7, khoj-assistant==0.1.8, khoj-assistant==0.1.9, khoj-assistant==0.2.0, khoj-assistant==0.2.1 and khoj-assistant==0.2.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    khoj-assistant 0.2.5 depends on torch==1.13.1
    khoj-assistant 0.2.1 depends on torch==1.12.1
    khoj-assistant 0.2.0 depends on torch==1.12.1
    khoj-assistant 0.1.10 depends on torch==1.12.1
    khoj-assistant 0.1.9 depends on torch==1.12.1
    khoj-assistant 0.1.8 depends on torch==1.12.1
    khoj-assistant 0.1.7 depends on torch==1.12.1
    khoj-assistant 0.1.6 depends on torch==1.11.0
    khoj-assistant 0.1.5 depends on torch==1.11.0
    khoj-assistant 0.1.4 depends on torch==1.11.0
    khoj-assistant 0.1.3 depends on torch==1.11.0
    khoj-assistant 0.1.2 depends on torch==1.11.0
    khoj-assistant 0.1.0 depends on torch==1.11.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

**Comment by debanjum** [comment]
Hi @usman-ghani-khan , thanks for reporting your issue with installing the Khoj python package. 

You may have a different version of (py)torch already installed (and used by some other python package). The existing torch version seems to be causing the confict with the torch version required by Khoj

1. Can you check what, if any, [version of torch is already installed](https://varhowto.com/check-pytorch-version/) with `pip show torch`?

2. To avoid dealing with the conflict, you can install khoj in a separate [python virtual environment](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) with:
   ```shell
    # create python virtual environment
    python -m venv .khoj_venv
    # activate virtual environment
    source .khoj_venv/bin/activate
    # install khoj in virtual environment
    pip install khoj-assistant
    # start khoj
    khoj 
   ```

**Comment by usman-ghani-khan** [comment]
Do I need to install pytorch to install khoj?

**Comment by debanjum** [comment]
Ah, it's unfortunate that installing Khoj in a virtualenv didn't just work.

> 1. Can you check what, if any, version of torch is already installed with `pip show torch`?

What was the result of running the above command? This will help verify if an existing version of torch is already installed on your machine (and/or virtualenv).

To help debug the issue further, could you share the following:
1. What is the operating system you're trying to install Khoj on?
2. Can you share screenshots of the commands you're running and their error logs when trying to install Khoj?

**Comment by debanjum** [comment]
> Do I need to install pytorch to install khoj?

No, you do not need to manually install pytorch. It should automatically get installed as a dependency when you install the khoj python package

**Comment by usman-ghani-khan** [comment]
When I run `pip show torch`, it gives this warning: 
`WARNING: Package(s) not found: torch`

My operating system is Windows 11.

Here are the screenshots:
![pip show torch](https://user-images.githubusercontent.com/82443800/216210610-73715dee-a4d7-4679-9801-04c49fae5766.png)
![pip install khoj](https://user-images.githubusercontent.com/82443800/216211059-f21bb9b0-a981-4afa-ade4-0b8edea95140.png)

**Comment by debanjum** [comment]
Thanks for sharing screenshots and more details on the issue you are facing.

> When I run pip show torch, it gives this warning:
> WARNING: Package(s) not found: torch

Seems like my "*conflicting version of pytorch already installed as dependency*" hypothesis was incorrect

### New Hypothesis
Looking at the error logs you shared more carefully, it seems like the `pip install` command is trying to install multiple(all?!) versions of khoj. But we just want to install the latest version of khoj (i.e `0.2.5` currently).

### Next Steps
1. Could you check if forcing pip to install only the specified version of khoj fixes your issue. That is, run `pip install khoj-assistant==0.2.5`
2. Can you also share your python version (`python -V`) and pip version (`pip -V`)?
3. I will try reproduce the installation issue you are facing on a windows machine

**Comment by usman-ghani-khan** [comment]
I was able to install `khoj` by downgrading python from version 3.11 to 3.9

**Comment by usman-ghani-khan** [comment]
I was able to successfully install `khoj` but when I run khoj command i get this error
`Traceback (most recent call last):
  File "c:\users\arshk\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\arshk\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\arshk\AppData\Local\Programs\Python\Python39\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "c:\users\arshk\appdata\local\programs\python\python39\lib\site-packages\src\main.py", line 85, in run
    main_window = MainWindow(args.config_file)
  File "c:\users\arshk\appdata\local\programs\python\python39\lib\site-packages\src\interface\desktop\main_window.py", line 62, in __init__
    self.search_settings_panels += [self.add_settings_panel(current_content_config, search_type)]
  File "c:\users\arshk\appdata\local\programs\python\python39\lib\site-packages\src\interface\desktop\main_window.py", line 87, in add_settings_panel
    current_content_files = current_content_config.get('input-files', [])
AttributeError: 'NoneType' object has no attribute 'get'`
![khoj error](https://user-images.githubusercontent.com/82443800/216874461-60cca826-7bcb-46ab-a033-3617cd3de07d.png)

**Comment by debanjum** [comment]
Can you delete the `.khoj` folder (it should be at `C:\users\arshk\.khoj`) and run the `khoj` command again? It seems like your `~/.khoj/khoj.yml` config file maybe corrupted.

**Comment by eduongAZ** [comment]
I tried using python 3.11 for khoj as well. I believe the problem is Torch does not support python 3.11. The pip installation process hang when trying to install Torch.

Once I downgraded to Python 3.10, it was able to install Torch.

Unfortunately I did not record the error message.

**Comment by debanjum** [comment]
Ah @eduongAZ, thanks for looking into this, that makes much more sense. See [this issue](https://github.com/pytorch/pytorch/issues/86566) and [milestone](https://github.com/pytorch/pytorch/milestone/35) to track pytorch support for python 3.11. Until then folks facing issues with installing khoj using python 3.11 will have to downgrade to python 3.10.

I'll update khoj to limit working with python versions below 3.11 until pytorch starts supporting python 3.11 as well and close this issue for now. As nothing can be done about it.

**Comment by usman-ghani-khan** [comment]
I am using khoj in obsidian, but there is no option to specify the path of my obsidian vault.
![obsvault](https://user-images.githubusercontent.com/82443800/218294953-7bdb39e3-4b05-44d4-ae95-e7ac908c7cac.png)

**Comment by debanjum** [comment]
The Khoj Obsidian plugin automatically configures the vault in which you installed the plugin as the vault for the khoj backend to index

**Comment by usman-ghani-khan** [comment]
> The Khoj Obsidian plugin automatically configures the vault in which you installed the plugin as the vault for the khoj backend to index

But when I search the notes in obsidian, then I get a message showing that there are no notes??

**Comment by debanjum** [comment]
That maybe because there was an issue with the khoj backend indexing your notes. Can you share screenshots of what you see once your start your khoj backend in a [new discussion topic](https://github.com/debanjum/khoj/discussions/new?category=q-a)?
